### ISSUE TITLE
Render urban place= values: suburb, quarter, neighbourhood

### ISSUE THREAD

**Issue by wmisener** [osm-americana/openstreetmap-americana#1058]
Americana already renders `place=city`, `town`, and `village`, but lacks urban districts/neighborhoods, usually tagged as `place=suburb`, `quarter`, and `neighbourhood`. These named areas are usually part of a larger `city` or `town` rather than being their own distinct places, but they are nonetheless important for wayfinding and orientation in urban regions.

Per [the wiki](https://wiki.openstreetmap.org/wiki/Key:place#Populated_settlements,_urban), each tag represents a distinct size/importance of the area, with suburb > quarter > neighbourhood (note: `place=suburb`, a major district of a city, is distinct from the American English definition of "suburb", which is typically a distinct municipality in the area surrounding a city). In my experience, in US usage the distinction between each tag is only loosely followed and convention is highly variable from city to city. Therefore, I suspect rendering all three tags similarly but with slight differences will be the best approach.

In my mind, a typical treatment of neighborhoods on US city maps would be all-caps labels and/or a light font color, typically to make neighborhood labels less prominent than other labels. We'd have to make sure any choices sufficiently distinguish these places from labels for roads and independent places: I think the all-caps would accomplish this (we currently use an all-caps treatment for state labels, but I don't think the risk of confusion is too high). I think just a label without an icon makes sense given the inherent area nature of neighborhoods, and would further distinguish them from independent places which get a dot.

Here's an example from a AAA map I have. In this one, the neighborhoods are in light blue. Other samples welcome!
![IMG_7553](https://github.com/ZeLonewolf/openstreetmap-americana/assets/58491489/bbf84ab5-98f0-439f-aefa-c028a036d0c2)

There are also other urban place tags: `place=borough` appears to be used [essentially only in Pennsylvania](https://wiki.openstreetmap.org/wiki/Tag%3Aplace%3Dborough) by an import to represent a local administrative classification. It's [probably a tagging error](https://osmus.slack.com/archives/C066VNZEGQ7/p1712353370573829?thread_ts=1712178270.196629&cid=C066VNZEGQ7), so that should probably not be rendered. Smaller divisions, such as `city_block` and `plot`, are very rare in the US. So I don't think Americana needs to render them at this time.

**Comment by 1ec5** [comment]
> I think just a label without an icon makes sense given the inherent area nature of neighborhoods, and would further distinguish them from independent places which get a dot.

At the zoom levels where we’d label neighborhoods, I think it would be misleading to put a dot on any kind of place that isn’t a specific point of interest.

**Comment by ZeLonewolf** [comment]
I agree with the comments about the all-caps labels and no icons.  Unspoken is also to make sure they're at a zoom level where neighborhood-level labels make sense.  I think de-conflicting with POIs may pose a challenge so we might need to think about a sensible lower AND upper zoom to support displaying neighborhood labels when it makes sense.

The blue labels are growing on me, and with water features in italics, they shouldn't even conflict.  It's worth trying.

**Comment by wmisener** [comment]
I agree that these kind of labels should have lower and upper zoom levels for rendering, just as independent `place=` values currently do in the style. For comparison/reference, the (raster) zoom levels at which labels appear in Carto: 
- `suburb` appears between z12-16
- `quarter` appears between z14-16
- `neighbourhood` appears between z15-19

These certainly have room for tweaking (and I do find anecdotally that showing the neighborhood labels at z19, Carto's highest zoom level, can collide POI labels out), but they give a general idea of a possible progression.
