### ISSUE TITLE
Shield icons mismatched in taginfo

### ISSUE THREAD

**Issue by claysmalley** [osm-americana/openstreetmap-americana#1155]
The [Taginfo project page](https://taginfo.openstreetmap.org/projects/osm_americana) is displaying the wrong icons for various values of `network=*`:

![image](https://github.com/user-attachments/assets/5c9a6c05-77dc-4e12-b059-7f00bc20b705)

**Comment by ZeLonewolf** [comment]
I'm wondering if this could be a CDN caching thing.  I believe the filenames are generated with an incrementing number, so they might change if new designs get added.

**Comment by ZeLonewolf** [comment]
These shields are pushed to github pages, e.g.:
https://americanamap.org/shield-sample/shield_24.svg

If we change the shield designs it'll be a day lag before the new taginfo file catches up.  That could be one possible issue, but I don't think we changed those recently?

**Comment by ZeLonewolf** [comment]
Ok so I'm looking at taginfo now and things seem correct, can someone confirm?

**Comment by 1ec5** [comment]
Yes, looks good to me. Do we want to change the format to be more resilient to such changes, or is it not a big enough deal to fuss over?

**Comment by ZeLonewolf** [comment]
yes, ideally the format should use names with substrings like "_blue_pentagon_" and not rely on an arbitrary numbering system. Although this is a pretty minor issue.

**Comment by claysmalley** [comment]
Closing this for now. If it happens again, let's consider a more error-proof way of naming these icons.
