### ISSUE TITLE
Several bannered shields showing up with wrong icon and/or color

### ISSUE THREAD

**Issue by claysmalley** [osm-americana/openstreetmap-americana#1160]
Many bannered shields are showing up with the wrong icon or color. This appears to have been caused by #1073.

Examples include bannered Interstate routes:

[![image](https://github.com/user-attachments/assets/480cf724-7631-478e-ac7d-a00361b2378e)](https://americanamap.org/#map=7.53/41.96/-76.736/0/1)

_Originally posted by @jleedev in https://github.com/osm-americana/openstreetmap-americana/issues/1158#issuecomment-2358205506_

Business Farm-to-Market Roads in Texas are also affected:

[![image](https://github.com/user-attachments/assets/e510171f-81f5-457b-82f0-51506bddd8b2)](https://americanamap.org/#map=14.54/30.00088/-95.26844)

**Comment by StretchLongfellow** [comment]
Just beat me to it. I noticed that Alt Interstate routes are showing up with a business shield as well, like the Future Interstate you screencapped.
