### ISSUE TITLE
protected area is rendered over features

### ISSUE THREAD

**Issue by RedAuburn** [osm-americana/openstreetmap-americana#1161]
Looks like https://www.openstreetmap.org/relation/10764047 is being rendered over everything

![image1](https://github.com/user-attachments/assets/b7c8adfa-1809-41a0-8e68-e4fca0dfa191)

**Comment by ZeLonewolf** [comment]
This looks like the expected rendering.  Not all features are implemented yet.  For example, we are not yet rendering paths (#216). Are there features we are presently rendering that are overlapped by protected areas?

**Comment by RedAuburn** [comment]
ah, you're right 👍️
i wouldn't expect the world heritage site to be rendered as a filled-in area, it might be better to switch to a line style like borders (with a centred label on lower zooms). Alternatively, Carto doesn't render it at all.
