### ISSUE TITLE
County Road/Route/Highway M1-6 sign not showing for multiple counties in colorado

### ISSUE THREAD

**Issue by GarliccBread1** [osm-americana/openstreetmap-americana#1175]
The county road shield doesn't render even though the relations are set up correctly with the right network. the Americana map does work for counties like Grand County or Douglas County, but for Elbert, Arapahoe, Jefferson, and Clear Creek, it just shows a hovering number over the road with no shield. The networks that aren't showing county road shields when the road has a relation on it are- US:CO:Arapahoe, US:CO:Jefferson, US:CO:Clear Creek, US:CO:Elbert. Could this be fixed for these roads in these counties tied to the route relations to render the M1-6 shield? Thanks!

Shields not working in the four counties I listed:
![Screenshot 2024-12-02 135922](https://github.com/user-attachments/assets/48d283fe-0cd7-4e78-9a09-48435f2c4ca0)
![Screenshot 2024-12-02 135135](https://github.com/user-attachments/assets/e55e4adf-134b-43ba-acc7-731bf0256da8)
![Screenshot 2024-12-02 135213](https://github.com/user-attachments/assets/0586d3f0-72df-4b4d-a887-567b097c7a67)
![Screenshot 2024-12-02 135253](https://github.com/user-attachments/assets/50e66f66-4118-4e6c-9855-25130b0c9801)

Shields working in grand county:
![Screenshot 2024-12-02 135839](https://github.com/user-attachments/assets/ae49d037-11e5-42f1-83be-912c22d5f374)

**Comment by claysmalley** [comment]
We only support shields that exist on the ground, and not all counties actually use the blue pentagon shields. For [Clear Creek County Road 306](https://www.bing.com/maps?cp=39.76403%7E-105.63326&lvl=20.1&mo=om.1&pi=-3.6&style=x&dir=145.3) and [Elbert County Road 13](https://www.bing.com/maps?cp=39.433928%7E-104.606453&lvl=21.2&mo=om.1&pi=-0.8&style=x&dir=246.4), all I could find was a green blade sign, posted the same as a street name. If you can find examples of blue pentagon shields for these counties, please post them here.

That said, I managed to find some on-the-ground examples for [Arapahoe County Road 42](https://www.bing.com/maps?cp=39.594441%7E-104.796679&lvl=19.3&mo=om.1&pi=1.9&style=x&dir=31.7) and [Jefferson County Road 93](https://www.bing.com/maps?cp=39.655983%7E-105.191436&lvl=22.0&pi=-1.6&style=x&dir=34.6). I'll go ahead and add these to the list momentarily.

**Comment by GarliccBread1** [comment]
Clear Creek county started to replace the old green blade signs with these signs:
![Screenshot 2024-12-02 173443](https://github.com/user-attachments/assets/3f55f01f-35cd-4b55-84c8-590d2602fa44)
![Screenshot 2024-12-02 173512](https://github.com/user-attachments/assets/71a1ee2e-1b9d-40f1-9571-5ef0f4e740e7)
![Screenshot 2024-12-02 173536](https://github.com/user-attachments/assets/c8e00683-e68c-4341-b089-10b7bbdfc27e)
![Screenshot 2024-12-02 173713](https://github.com/user-attachments/assets/b281c062-1aa8-47fc-a369-a85cd7ba768b)
They're slowly changing to the M1-6 signs now on most county roads, like in Empire CO they're replacing old signs with the standard route marker next year.

And for elbert county, you're right, they seem to only just do the green signs.
Thanks!

**Comment by claysmalley** [comment]
I've proposed adding support for Clear Creek County in #1177. Note that `network=US:CO:Clear Creek` will need to be retagged to `network=US:CO:Clear_Creek` (with underscore) to be recognized by Americana.

**Comment by GarliccBread1** [comment]
sounds good thanks, I can easily fix that on the current relations in OSM! 
here's also some more signs that are popping up
![Screenshot 2024-12-05 020823](https://github.com/user-attachments/assets/de905660-25f3-49e0-8ef4-709be191665c)
