### ISSUE TITLE
Show highway names in users' language with gloss

### ISSUE THREAD

**Issue by adamfranco** [osm-americana/openstreetmap-americana#618]
Around the world there are many highways that have translated names tagged in OSM, but highway names are shown in Americana as the local name, which might not be understandable by the viewer, especially in cases where the script of the local language is not familiar to the viewer. As someone who doesn't read Hebrew, Arabic, or other non-latin scripts I'd expect to see my local language or at least a Latin scripts on road names.

Here's an example of the [Armenian Patriarchate (openstreetmap.org)](https://www.openstreetmap.org/way/265414845) in Jerusalem, which has Hebrew script as the local name, but has many translations.
[Armenian Patriarchate](https://www.openstreetmap.org/way/265414845) in Jerusalem.
![Screen Shot 2022-12-14 at 11 36 28 AM](https://user-images.githubusercontent.com/25242/207654168-888fe9dd-a9cf-4664-a589-67e0aa1e257f.png)

[Location in Americana](https://zelonewolf.github.io/openstreetmap-americana/#map=17/31.77716/35.22786)
![Screen Shot 2022-12-14 at 11 36 50 AM](https://user-images.githubusercontent.com/25242/207654240-33059cc9-f6f2-4041-ae43-a5f2cad0cae6.png)

As with place labels, glossing with the local name strings would make the rendering useful for travelers so that can compare street signs while walking about while still relating the translated name to guidebooks or other materials translated into their language.

**Comment by 1ec5** [comment]
https://github.com/ZeLonewolf/openstreetmap-americana/pull/578#issuecomment-1328173700 implemented language switching for road names, but OpenMapTiles only contains names in English, German, and the local language: openmaptiles/openmaptiles#769.

**Comment by 1ec5** [comment]
Oh, looks like the localization functionality broke for streets has broken since that comment.

**Comment by ZeLonewolf** [comment]
That cited openmaptiles issue (769) is about removing the legacy `name_en`, `name_de`, etc., in favor of colon-separated name tags e.g. `name:en`, `name:de`, etc.  If language name support is missing on roads but should be there, that needs to be a separate OMT ticket.

**Comment by 1ec5** [comment]
#619 fixes the regression introduced in #471 so that road name labels are once again localized in the user’s preferred language (as long as the user prefers English or German).

**Comment by 1ec5** [comment]
> As with place labels, glossing with the local name strings would make the rendering useful for travelers so that can compare street signs while walking about while still relating the translated name to guidebooks or other materials translated into their language.

In fact, navigation applications that localize place names and POIs generally keep street names unlocalized for this reason. A gloss would make some sense for this style, which is not heavily focused on the real-time turn-by-turn navigation use case. If we simply set `text-field` to `localizedNameWithLocalGloss`, then the entire road name label could often get collided out by other things like route shields. As an alternative, we could add a separate symbol layer so it can participate independently in symbol collision. We would need to place the preferred-language name above the street line while placing the local-language name below the street line, but that could be confusing compared to an inline gloss.

**Comment by ZeLonewolf** [comment]
I just checked the tiles, and language tagging for streets does appear to be present:

![image](https://user-images.githubusercontent.com/3254090/208546531-7a453785-f947-4ac1-95ea-0c2fc94cb1f8.png)

**Comment by 1ec5** [comment]
[<img src="https://user-images.githubusercontent.com/1231218/208548854-53ca95d0-2d26-42bb-b134-ca2db2fa70de.png" width="177" alt="Ayalon South">](https://6ug7hetxl9.execute-api.us-east-2.amazonaws.com/data/v3/#18/32.09828/34.80262)

**Comment by ZeLonewolf** [comment]
This is a planetiler bug, logged in onthegomap/planetiler#419

Our code should be using `name:xx` tags and not `name_en` / `name_de`, etc tags.

**Comment by ZeLonewolf** [comment]
Thanks @zstadler for pointing out the problem in #624.

**Comment by zstadler** [comment]
I should have known it is a Planetiler issue rather than an OpenMapTiles issue. Otherwise, [Israel Hiking Map](https://israelhiking.osm.org.il/) would have been in serious trouble...

**Comment by 1ec5** [comment]
This is fixed. For example, [the streets in Winnipeg are in French](https://americanamap.org/#map=14.26/49.88553/-97.11543&language=fr).

**Comment by 1ec5** [comment]
Oh wait, the request was for bilingual labeling, so we’ll keep the issue open for that.

**Comment by 1ec5** [comment]
> As an alternative, we could add a separate symbol layer so it can participate independently in symbol collision. We would need to place the preferred-language name above the street line while placing the local-language name below the street line, but that could be confusing compared to an inline gloss.

This would probably result in the two labels colliding each other out too: maplibre/maplibre-style-spec#1432.
